name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t myapp .

      - name: Test container
        run: docker run myapp 5

      - name: Test container (fail expected)
        run: |
          docker run myapp || true
